source 'https://rubygems.org'

gem 'json-ld'
gem 'json-ld-preloaded'
gem 'rdf-rdfa'
gem 'rdf-microdata', '>= 3.1.3'
gem 'rdf-reasoner'
gem 'rdf-turtle'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.12.5'
gem 'nokogumbo', '>= 2.0.4'
gem 'equivalent-xml', '>= 0.6.0'

group :debug do
  gem 'byebug'
end
