source 'https://rubygems.org'

gem 'json-ld'
gem 'json-ld-preloaded'
gem 'rdf-rdfa', '>= 3.2.1'
gem 'rdf-microdata'
gem 'rdf-reasoner'
gem 'rdf-turtle'
gem 'rspec'
gem 'rake'
gem 'nokogiri'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
